### ISSUE TITLE
Feature Request - Memory information in Profiling & Statistics

### ISSUE THREAD

**Issue by ikb42** [medikoo/memoize#31]
How much RAM is being used to hold the current cache.

Great tool! Thanks!

**Comment by medikoo** [comment]
@ikb42 it's designed to be minimal, but surely depends on use case. You should measure it on your own

**Comment by ikb42** [comment]
That could be tricky, would require holding separate info about the cache that was in sync with whats in the cache.
A memory counter in the cache would be much better.

**Comment by medikoo** [comment]
@ikb42 it's JavaScript, there's no access to information how much memory is taken by each object
