### ISSUE TITLE
Register callback when cache reaches max size

### ISSUE THREAD

**Issue by theothermattm** [medikoo/memoize#36]
It would be nice to be able to register a callback when the cache reaches its max size.  Even better if the value being evicted could be accessed.

The use case I'm after is being able to log out when a cached method result is going to be evicted for debugging/perf analysis purposes.

I tried to use the dispose callback for this but realized it was only called when clear() is called.

Apologies if I missed something in the docs and if this is possible!

**Comment by theothermattm** [comment]
Sorry, my testing for this was faulty, realizing the dispose function is getting called.

**Comment by medikoo** [comment]
:)

**Comment by theothermattm** [comment]
Though actually, after I closed this I realized it would be great if there was the ability to have different callbacks for the clear of an entire cache and what gets called on a purge after the maxSize is hit. 

Helps with knowing when you're evicting things based on your set policy.  Just something to think about.  I can log a separate issue if you think it's a decent idea.

**Comment by medikoo** [comment]
@theothermattm is it just _nice to have_ or you have real use case, where you can benefit from that?

**Comment by theothermattm** [comment]
The use case is to know when things are being evicted via a set policy or when you're explicitly doing a clear.  For instance, in my application, it is valuable for me to know when I start evicting things and which things are being evicted.  This helps me with tuning cache sizes.

I say it's nice to have because right now in my disposer function, I'm using closure to check a flag that I toggle on and off to output a log message when something is disposed.  When I call clear() I unset the flag so I don't get any log messages, then I toggle it back on so that when things get evicted I get my log messages.

Hope that makes sense!

**Comment by medikoo** [comment]
@theothermattm thanks for explanation. However even if we would introduce callback for clear, dispose callbacks for consistency will have to be invoked anyway. So still you will need to rely on that custom flag, if I get things right. Nothing really will be improved.
