### ISSUE TITLE
Chaining off of cached Promise causes cached value to be modified

### ISSUE THREAD

**Issue by mrodrig** [medikoo/memoize#38]
I just recently found out that when using this library to memoize a function that returns a promise that if you chain a .then off the cached value and then return anything besides the original value (or don't return anything at all) then you will end up modifying the cached value to whatever you returned (or undefined if you don't return anything).

Example:
```javascript
'use strict';

var memoize = require('memoizee'),
	promise = require('bluebird');

var returnPromisifiedArray = function ( number ) {
	return new promise(function (resolve, reject) {
        resolve([{val : number}]);
    });
}

var returnTestArray = function ( numberInArray ) {
	console.log('Cache miss! Called with: ' + numberInArray);
	return returnPromisifiedArray(numberInArray);
};

var returnTestArrayMemoized = memoize(returnTestArray, {primitive: true, max: 1000});

var runTest = function () {
	return returnTestArrayMemoized(1)
		.then(function (value) {
			console.log(value);
			value = value.map(function(item) {
				item.badVal = 'fail';
				return item;
			});
			return value;
		}).catch(function (err) {
			console.log('unexpected error');
		});
};

runTest(); // Retrieves [ {a : 'b'} ] from the cache (expected value)
runTest(); // Retrieves [ {a : 'b', badVal : 'fail'} ] from the cache (not the expected value)
```

This example appears to be hitting line 78 and 86 in configure-map.js which is setting the cache to have the original return value and then later returns it, which potentially allows for modifications to be made to the cached value. 

Not sure if you consider this part of the scope of #35 or not, but I figured it couldn't hurt to log it here in case other people also run into this.

**Comment by mrodrig** [comment]
Also, if the value that is resolved in the Promise that is cached is an array of numbers then the cached value is not modified.

Example:
```javascript
'use strict';

var memoize = require('memoizee'),
	promise = require('bluebird');

var returnPromisifiedArray = function ( number ) {
	return new promise(function (resolve, reject) {
        resolve([number]);
    });
}

var returnTestArray = function ( numberInArray ) {
	console.log('Cache miss! Called with: ' + numberInArray);
	return returnPromisifiedArray(numberInArray);
};

var returnTestArrayMemoized = memoize(returnTestArray, {primitive: true, max: 1000});

var runTest = function () {
	return returnTestArrayMemoized(1)
		.then(function (value) {
			console.log(value);
			value = value.map(function(item) {
				item.badVal = 'fail';
				return item;
			});
			return value;
		}).catch(function (err) {
			console.log('unexpected error');
		});
};

runTest(); // Retrieves [ 1 ] from the cache (expected value)
runTest(); // Retrieves [ 1 ] from the cache (expected value)
```

Note that the only difference between the two examples is:
Cache Modification Example: ```resolve([{val : number}]);```
Cache Non-modification Example: ```resolve([number]);```

**Comment by medikoo** [comment]
@mrodrig this is expected and very natural behaviour when JavaScript is concerned, also it doesn't have to do anything with promises. You're test case can be much simpler:

```javascript
var memoizedFn = memoize(function (id) { return {}; });

var obj = memoizedFn('foo');
obj.hello = 'bar!';

var otherObj = memoizedFn('foo');
console.log(otherObj.hello); // bar
console.log(otherObj === obj); // true
```

If you use memoize to cache functions that return objects, you should expect same objects being returned on cache hit calls, and if one of consumers modifies result object, such modification will naturally be visible for all other consumers of object, and will remain across cache hits.

The one way to avoid it, is to clone object before you try to mess with it, or find some other way to store needed values.
