### ISSUE TITLE
how do I use in the browser?

### ISSUE THREAD

**Issue by hodeyp** [medikoo/memoize#40]
Hi, I am trying to use Webmake to generate a browser compatible build. I have built using `web make index.js bundle.js` and then included bundle.js in my index.html. 

However when I try to call memoize in my js I get an error memoize is not defined - how am I meant to call the function?

**Comment by medikoo** [comment]
_program.js_:
```javascript
var memoize = require('memoizee');

if (memoize) {
  console.log("Memoize is defined!");
} else {
  console.log("Memoize not working!");
}
```
Then in shell:
```
$ webmake program.js bundle.js
```

Of course memoize won't be visible outside the bundle, but it's how CJS works, it's perfect encapsulation you should not expect utilities to be exposed old school way on globals.
