### ISSUE TITLE
Easiest way to ignore an argument for memoization

### ISSUE THREAD

**Issue by bojand** [medikoo/memoize#44]
Let's say I have an async function:

```js
function verifyToken(token, fn) {
   ...
}`;
```
This can easily be momoized with something like:
```js
var memoized = memoize(verifyToken, {async: true, length: 1});
```
What if I have a function:
```js
function verifyToken(req, token, fn) {
  ...
}`;
```
where `req` is Express request object. I would **not** like the `req` value to be considered for hashing at all. We should still memoize results of `verifyToken` based on `token` value only. What's the easiest approach to accomplish this? Resolvers? Something like:
```
var memoized = memoize(verifyToken, {async: true, length: 2, resolvers: [Boolean, String]});
```
? This way `req` (which will always be there) will always just be coersed to `true` and `token` will be coersed to `String` as normal. Just want to check if this the best approach? Thanks!

**Comment by medikoo** [comment]
You can ignore arguments, but only trailing ones, not leading ones.

So I believe it would work as expected if you do:

```javascript
function verifyToken(token, req, fn) {
  ...
};
var memoized = memoize(verifyToken, { async: true, length 1 });
```

I'm closing it, as it's neither bug report nor feature request, still let's continue discussion

**Comment by bojand** [comment]
Thanks for the reply. Yea it's just a usage question, not a bug. Sorry i should have made it clearer... I don't have a choice of argument ordering due to contextual factors. so the argument order in function signature has to be `(req, token, fn)`. I imagine I could do something hacky-ish perhaps with lexical closur-ing and/or partial-ing + memo, but wanted to know if there was a simpler approach?

**Comment by medikoo** [comment]
The other approach would be to solve it via decorator pattern:

```javascript
var memoized = memoize(function (token, req, fn) {
 ...
}, { async: true, length 1 });

function verifyToken(req, token, fn) {
  return memoized(token, req, fn);
};
```
